# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 836181590fced52854a5fcf4fe08501c817c3cb37680beac2339224a76933084d9753be5fc51c59e8889f1a1570c721f00695fc1b55e467566fb753d7ee987d6

test:
  secret_key_base: 8426d4ed0d34fa235d1b307e19aa0a49eca2ff0e3351340c0db4aa417f1efc1848348c20eafa86629f3a6162f63144fb0eae67a1e9b3370fc786a89026581787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
